from dotenv import load_dotenv
import os
from pathlib import Path

if load_dotenv():
    print("API key loaded successfully.")
else:
    print("Warning: could not load API key. Check your .env file.")

def headliner(string:str):
    print("\n" + "="*40)
    print(string)
    print("="*40)

from llama_index.core import SimpleDirectoryReader, VectorStoreIndex


# Step 1: Setup
groundwork_docs = Path("../../lessons/06_AI_augmentation/resources/groundwork_docs")

assert groundwork_docs.exists(), f"Document directory not found: {groundwork_docs}"
print(f"Document directory found: {groundwork_docs}")


# Step 2: Load the Documents

raw_docs = SimpleDirectoryReader(str(groundwork_docs)).load_data()

print(f"\nLoaded {len(raw_docs)} documents:")
for doc in raw_docs:
    print(f"  - {doc.metadata.get('file_name', 'unknown')}")


# Step 3: Build the Index and Query Engine

index = VectorStoreIndex.from_documents(raw_docs)
query_engine = index.as_query_engine(similarity_top_k=3)

print("\nIndex built successfully. Ready to answer questions.")


# Step 4: Query the Assistant

questions = [
    "What are Groundwork's hours on weekends?",
    "Do you offer any dairy-free milk options?",
    "How does the loyalty program work?",
    "How did Groundwork Coffee get started?",
    "Do you offer catering or wholesale orders?",
]

headliner("Step 4: Query the Assistant")

for q in questions:
    print(f"\nQuestion: {q}")
    response = query_engine.query(q)
    print(f"Answer: {response}")

    if response.source_nodes:
        top_node = response.source_nodes[0]
        doc_name = top_node.node.metadata.get("file_name", "unknown")
        score = top_node.score
        snippet = top_node.node.text[:200]
        print(f"Top source: {doc_name} | Score: {score:.4f}")
        print(f"Snippet: {snippet}")

# Considering the outcomes of Step 4:
# Each of the five responses was precise, self-assured, and free of hedging.

# Hours: faq.txt received a score of 0.81 and provided accurate answers with precise times.

# Dairy-free: Seasonal_specials.txt (0.77) rather than menu.txt was the best source.
# The retrieval was taken from the seasonal document since "dairy-free" was included in the 
# item descriptions, even though the response (oat, almond, and soy at no additional cost) 
# remained accurate. Apparently, the precise word is not used on the main menu. Semantic 
# search did exactly what it was meant to do—find the correct answer from an unexpected source.

# Loyalty program: 0.77 for faq.txt. The response was precise and detailed:
# You can join for free, register online or at the register, and get 1 point for every dollar 
# or 100 points for a complimentary drink. Nothing more than what the document supports was added.

# Origin story: our_story.txt received the highest score in this batch, 0.89.
# The response was precise: Maya Torres and Sam Okafor, Asheville, North Carolina, created in 2018.
# The most thorough and assured response was generated by a high retrieval score.

# Catering: wholesale_catering.txt received a score of 0.85. Given the contents of the document,
#  the model's brief but accurate response was "yes, available." It was not overly detailed.


# Step 5: Find a Failure

headliner("Step 5: Find a Failure")

# I'm specifically inquiring about catering pricing because it necessitates 
# merging data from two sources (the catering document and any existing pricing
# information), and pricing is sometimes ambiguous or nonexistent in these 
# types of documents. The model must either acknowledge its ignorance or piece 
# together two pieces.
failure_query = "How much does catering cost per person for a corporate event?"

print(f"\nFailure query: {failure_query}")
failure_response = query_engine.query(failure_query)
print(f"Answer: {failure_response}")

print("All retrieved source nodes:")
for i, node in enumerate(failure_response.source_nodes):
    doc_name = node.node.metadata.get("file_name", "unknown")
    score = node.score
    snippet = node.node.text[:200]
    print(f"  Node {i+1}: {doc_name} | Score: {score:.4f}")
    print(f"  Snippet: {snippet}")

# Why I thought this would be challenging:
# Because it is dependent on headcount and menu choice, small businesses 
# seldom disclose catering pricing per person in flat-rate form.
# Without providing a price quote, the documents most likely describe the 
# availability of catering. The model is forced to either fabricate or hedge as a result.

# What truly took place:
# The top node was wholesale_catering.txt (0.79), followed by menu.txt (0.75) 
# and faq.txt (0.72). The retrieval was adequate. Although the correct paperwork 
# was found, it lacks precise per-person cost. In response, the model said, "pricing 
# varies based on package and event size, contact us for a quote." Although that is 
# a non-answer, it is technically correct. It doesn't really address the question, 
# but it sounds useful.

# Observation of tone:
# Despite having no actual data to work with, the model's tone remained confident 
# and fluid. "Pricing varies based on the package chosen" appears to be an 
# informative statement, but in business jargon, it is just the model rephrasing 
# "I don't have that information." It never expresses uncertainty or states 
# "I don't know." This is the risky pattern: a well-written non-answer that 
# the the reader may take at face value without recognizing it. The lesson is that 
# RAG does not compel the model to acknowledge ignorance, and grammatical assurance 
# is not the same as accuracy.

# What I would alter
# Include a retrieval confidence gate that returns a pre-written fallback, such as 
# "I don't have enough information to answer that accurately," if all node scores fall 
# below a threshold, such as 0.80 for particular factual queries. Please get in touch 
# with us directly. These scores—0.79, 0.75, and 0.72—were all below a fair cutoff point 
# for a particular pricing query. Instead of a smooth non-answer, that ought to have caused a fallback.


# Step 6: Reflection

# Manual semantic RAG versus LlamaIndex line count:
# It required around 80–120 lines to implement chunking, embedding, storage, similarity search, 
# and prompt injection from scratch in the lesson's manual semantic RAG.
# This project's LlamaIndex version accomplishes the same task in roughly five lines:
# load documents, establish an index, develop a query engine, and make a call.query(). 
# That's about a 15–20x code reduction. This indicates that complex issues 
# (chunk sizing, embedding batching, cosine search, prompt templating) have previously 
# been resolved in a tested and maintained manner by frameworks such as LlamaIndex. 
# Although writing it from scratch can help you understand what's going on behind the 
# scenes, you would never do that in production.

# An alternative scenario in which RAG truly adds value
# internal knowledge base of a hospital. Physicians and nurses require prompt, precise 
# responses regarding medication interactions, current clinical standards, and hospital-specific 
# protocols. These documents are too large to refine and are updated on a regular basis.
# A RAG system that is indexed over clinical PDFs and policy documents could enable staff 
# members to ask natural language queries and receive well-founded responses that clearly 
# trace their origins back to the original materials. Here, it's crucial to be able to update 
# the index without retraining the model.

# One mode of failure that RAG is unable to completely stop:
# When responding, the model may still experience hallucinations even if retrieval brings 
# up the correct material. This occurs when the model "fills in the gaps" with credible-sounding 
# information from its training data instead of stating it doesn't know when the retrieved chunks 
# are pertinent but incomplete. The creation step created details that the context did not support, 
# yet the retrieval functioned as intended. Evaluations of faithfulness can identify this after the 
# fact, but they don't stop it before it happens. The only effective mitigations are post-generation 
# verification and quick engineering, which specifically tells the model to say "I don't know" instead 
# of speculating.